### ISSUE TITLE
Killed unit turns into carcass

### ISSUE THREAD

**Issue by erlend-sh** [amethyst/evoli#103]
A simple feature to get us closer to life-like behaviors would be for killed units to not disappear instantaneously, instead turning into dead carcasses.

The predators in turn would remain in place to feed on these carcasses until there's no more meat to feed on. In our current system a unit gets fed at the moment when it terminates another unit. That will no longer be the case with the introduction of carcasses.

Upon changing from `alive` to `dead`, the herbivore unit's model should change. Something good might be found on http://quaternius.com/assets.html, but for the first take it might be best to just change its color to something like grey.

Relevant system backstory:
- https://github.com/amethyst/evoli/pull/21
- https://github.com/amethyst/evoli/pull/69

---

After implementing this for herbivores we should also look at applying the same method to plans, as they will behave very similarly to carcasses. Herbivores should munch on them for quite a while before they're completely removed.

**Comment by Brainshack** [comment]
New to learning rust and amethyst and I thought this might be a good learning experience, therefore i started a branch on this.

**Comment by erlend-sh** [comment]
Yay! Let us know on here or on the Discord chat if you have any questions.
