### ISSUE TITLE
Set up CI with that checks fmt, runs `cargo check` and runs the tests

### ISSUE THREAD

**Issue by marotili** [amethyst/evoli#22]
We should set up a basic CI that runs
- `cargo fmt -- --check`
- `cargo check`
- `cargo test --all`

**Comment by marotili** [comment]
@erlend-sh My knowledge here is very limited. Imo we should use the same stack as Amethyst. Would that be possible?

**Comment by erlend-sh** [comment]
[Moved to forum](https://community.amethyst.rs/t/set-up-ci-with-that-checks-fmt-runs-cargo-check-and-runs-the-tests/775?u=erlend_sh) since it's at the discussion stage, not ready for implementation.
