### ISSUE TITLE
Basic background terrain render

### ISSUE THREAD

**Issue by erlend-sh** [amethyst/evoli#25]
Let's not have our creatures occupy an empty abyss any longer. We wanna build a flat, square map with no special characteristics for starters, but more interesting iterations will eventually follow

TODO is pretty much:

- find a good, free tileset (ideally it goes well together with the low-res style of sprite-gen: https://github.com/tversteeg/sprite-gen)
- put together a square area in Tiled editor
- export it and share it in #showcase-team . 

and if you feel like it you could also do the implementation part:

- make Tiled export work in Amethyst via tiled-rs
- fit the square area made in Tile into the square playing area of Evolution Island

**Comment by erlend-sh** [comment]
Affected by:
https://community.amethyst.rs/t/evoli-art-direction/773/2?u=erlend_sh

**Comment by sunreef** [comment]
This issue is addressed in #90 and #91. Since we moved from 2D to 3D, there is no tileset planned. The ground is just a smooth mesh for now.

**Comment by erlend-sh** [comment]
Yeah I think our definition of “background terrain” has changed enough that this issue is irrelevant. Closing.
