### ISSUE TITLE
Basic ambient background music loop

### ISSUE THREAD

**Issue by erlend-sh** [amethyst/evoli#26]
The looping ambient track [has already been created](https://community.amethyst.rs/t/evoli-mvp-implementation-tracker/537/6?u=erlend_sh).

What remains is playing this track on a loop once the game starts.

**Comment by marotili** [comment]
The pong example should be a good starting point. https://github.com/amethyst/amethyst/blob/v0.10.0/examples/pong/audio.rs

Check out the amethyst repository and run `cargo run --example pong` to run the example.

This file is responsible for setting up the background music: https://github.com/amethyst/amethyst/blob/v0.10.0/examples/pong/audio.rs

**Comment by nicklasmoeller** [comment]
I made an attempt on this one, as referenced.

**Comment by marotili** [comment]
Implemented in #35
