### ISSUE TITLE
Add possibility to speed up the game by a factor of 2

### ISSUE THREAD

**Issue by marotili** [amethyst/evoli#28]
Users should be able to speed up the simulation. Speeding up should be possible by using the `+` key and going back to normal speed should be done using the `-` key.
If any issues arise, e.g. collision doesn’t work anymore, we ignore it for now or create follow up issues.

Ambitious implementers don't have to stop at 2x speedup. 🚀

**Comment by khskarl** [comment]
I think this may be a good first issue, so I added the label :). Any thoughts?

**Comment by erlend-sh** [comment]
Where would someone new to Evoli begin to look in order to implement this? Would I start by looking at https://amethyst.rs/book/latest/concepts/state.html same as #27?

**Comment by erlend-sh** [comment]
Completed in #33
