### ISSUE TITLE
Undefined target for Carnivores cause them to walk constantly in one direction

### ISSUE THREAD

**Issue by khskarl** [amethyst/evoli#37]
## Description
`Carnivores` start walking eternally in one direction hoping to find heaven when there are no `Herbivores` within their range. 

## How to reproduce 
Start the game and wait until all Herbivores are dead.

## Video
https://s1.webmshare.com/oGoMo.webm
The bug happens around 0:04

## Additional notes
This kind of bug will probably be easier to debug once we get #29.

**Comment by marotili** [comment]
Fixed in #39
